export const periodsByFrequency = {
  monthly: [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December',
  ],
  quarterly: ['Q1', 'Q2', 'Q3', 'Q4'],
  semiannual: ['S1', 'S2'],
  yearly: ['Yearly'],
  weekly: Array.from({ length: 52 }, (_, i) => `Week ${i + 1}`),
}
